name: Build and Push to Build Branch

on:
  pull_request:
    types: [closed]
    branches:
      - development # Triggers when a PR is opened against development

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy to Build Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # ONLY files in dist move to the build branch
          branch: build # The target branch
          clean: true # Deletes everything else (README, LICENSE, etc.)
          commit-message: "Deploying to build branch from PR #${{ github.event.pull_request.number }}"

      - name: Read Version
        id: version
        run: |
          VERSION=$(cat VERSION)   # a VERSION file must be in the repo root
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Tag for Release
        run: |
          git fetch --all
          git checkout build
          TAG="build-${{ github.run_number }}"
          git tag -a "$TAG" -m "Release from commit ${{ github.sha }}"
          git push origin "$TAG"
